### ISSUE TITLE
M3C2 from command line and in silent mode cause gui error

### ISSUE THREAD

**Issue by LiorRaines** [CloudCompare/CloudCompare#1039]
Describe the bug:
When running M3C2 from command-line and with -SILENT flag , it cause qt.qpa.screen QXcbConnection: Could not connect to display error

How to reproduce:

I am running CloudComapre command-line interface like that "/snap/bin/cloudcompare.CloudCompare -SILENT -O target_cloud.ply -O source_cloud.ply -M3C2 m3c2_params.txt"

Expected behavior:
I expect that when setting -SILENT there will be only outputs to the terminal, and it will not try to connect to the display

Your environment:

CC Version (or git hash/tag): 2.10.2
OS & Version: Ubuntu 18.04
Qt Version (if compiling): 5.5.1

**Comment by dgirardeau** [comment]
I fear you would have the same issue with any command line option actually (have you tried with the first -O option only for instance?)

The issue is that the command line mode is only a kind of 'hack' of the graphical version (it's the same executable, that relies on the default Qt graphical application, etc.). It's just that the graphical interface is never shown. But everything to display it is allocated by Qt when launching the application...

**Comment by WargodHernandez** [comment]
Not sure if any of these are viable I'm not a huge linux guy, but I have seen some workarounds for this same error for other programs.
This project suggests a patched QT install https://github.com/mileszs/wicked_pdf/issues/723

Another common suggestion is to run an X server and then run the following command prior to the CC command 
`export DISPLAY=:0.0`

And here is a thread on possible modifications to try to support a headless environment in a graphical QT program
https://stackoverflow.com/a/14388074

**Comment by LiorRaines** [comment]
> Another common suggestion is to run an X server and then run the following command prior to the CC command
> `export DISPLAY=:0.0`
> 

that did the trick and made it work.
Thank you very much, it was a huge help
