### ISSUE TITLE
Remove RGB values in Command Line Mode

### ISSUE THREAD

**Issue by GreKro** [CloudCompare/CloudCompare#1077]
Hello everyone, 

I would like to prepare my point clouds in such a way that the output files store X, Y, Z, Nx, Ny, Nz and are stored in an ASCII file. 

As an input file, I have LAS files with many Scalar Fields and R,G,B values. When I used command line mode I'm able to remove ScalarFields but not RGB values. 
Does anyone or @dgirardeau  have an idea of how to walk around it in CC ? 

I use this CLM syntax:

CloudCompare -SILENT -NO_TIMESTAMP -C_EXPORT_FMT ASC -EXT txt -AUTO_SAVE OFF -O test.las -REMOVE_ALL_SFS -OCTREE_NORMALS 0.05 -ORIENT_NORMS_MST 10 -SAVE_CLOUDS FILE test_normals.txt

I attached to this issue my test LAS data.
[test.zip](https://github.com/CloudCompare/CloudCompare/files/4386156/test.zip)

@dgirardeau maybe you will consider adding an option to the command line mode in the future something like -REMOVE_RGB, I think it would be valuable. 

BTW.
I use CloudCompare v.2.11 beta on Windows 10 OS

Best regards,

**Comment by rjanvier** [comment]
it is something you could handle on Unix like systems with a command like `cut`  maybe you could try using [this](https://stackoverflow.com/questions/24634022/what-is-an-equivalent-of-nix-cut-command-in-powershell) on windows. Instead of -REMOVE_RGB if think it should be wise to add a `cut` like flag to CC command line to give ability to select a bunch of arbitrary fields.

**Comment by GreKro** [comment]
@rjanvier thanks for the response, at the moment  I'm doing it in a similar way.
It would be great if there was such an option directly in CC.
 Yes, definitely your idea with "cut" flag in CLI would be great.

**Comment by dgirardeau** [comment]
For now I added two options 'the old way' (-REMOVE_RGB and -REMOVE_NORMALS)
