### ISSUE TITLE
Compiler warning: potential divide by 0 in ccGBLSensor

### ISSUE THREAD

**Issue by asmaloney** [CloudCompare/CloudCompare#1132]
**Describe the bug**

From the CI when building on Windows:

D:\a\CloudCompare\CloudCompare\libs\qCC_db\ccGBLSensor.cpp(290): warning C4723: potential divide by 0 [D:\a\CloudCompare\CloudCompare\build\libs\qCC_db\QCC_DB_LIB.vcxproj]

**Your environment**
 - CC Version (or git hash/tag): master

**Comment by dgirardeau** [comment]
Yes I know this warning, but we do test before that Sz if inferior to 1, which means that Sx^2 + Sy^2 is necessarily above zero ... because S is a normalize vector :D. Of course the compiler can't deduce that on its own...

Not sure how to remove this warning.

**Comment by WargodHernandez** [comment]
https://www.fluentcpp.com/2019/08/30/how-to-disable-a-warning-in-cpp/

**Comment by WargodHernandez** [comment]
Do we want to add a header with various compiler/warning defines so we can keep all the define and pragma stuff centralized. And then just adopt a policy for minimal use and at least a minimal group consent before use?
I have considered disabling that warning for this issue since it shows up on visual studio whenever compiling the full project. It makes looking for real issues harder having it.

**Comment by dgirardeau** [comment]
Ah! I knew this way to mute a specific warning, but I was more thinking about a way to change the code without make it less efficient actually. I think I know how to do it, I'll try something.

**Comment by dgirardeau** [comment]
Should be fixed by ebe93b6fd4aa3a2629ce7f249df38067cb3a61d6
