### ISSUE TITLE
Unable to export nested structures in BIN file

### ISSUE THREAD

**Issue by virtualarchitectures** [CloudCompare/CloudCompare#1266]
As described in forum post [Help exporting nested structures in BIN file](http://www.cloudcompare.org/forum/viewtopic.php?t=4015), points in deeper levels of the BIN file hierarchy are not output when saving the files to another format.

1. Open BIN files with a nested hierarchy of more than two layers. 
2. Select the point cloud to be exported
2. Click on 'Save'
3. Save to another format such as .xyz
4. Open the file(s) in another application. Points in nested layers will be missing.

**Expected behaviour**
If the top level of the point cloud is selected to be saved all points in nested layers should also be saved unless the user explicitly chooses to exclude them. 

**Your environment**
 - CC Version (or git hash/tag): v2.10.2 Zephyrus
 - OS & Version: Windows 10

**Comment by dgirardeau** [comment]
Nope, this is not how it works, sorry. Each point cloud / 3D entity is independent. We just have a hierarchy of 3D entities.

If you want to save all entities at once, you would have to select the parent 'group' (and not the point cloud). However in this case you'll see that ASCII/TXT export is unavailable since this file format can only save one cloud at a time. Only a few formats are able to save multiple clouds, and even less with the hierarchy structure.

If you want to save all points in a single ASCII/TXT file, you'll have to select all of them (there are multiple ways to do it) and then use the 'Edit > Merge' option.
