### ISSUE TITLE
Can't open precompiled packages on MacOS Catalina

### ISSUE THREAD

**Issue by imrehg** [CloudCompare/CloudCompare#1267]
**Describe the bug**

When using the MacOS binaries on Catalina (MacOS 10.15.x), can't open with this error:

<img width="532" alt="Screenshot 2020-06-09 17 47 36" src="https://user-images.githubusercontent.com/38863/84178637-a3438800-aa7c-11ea-9149-de677f27858b.png">

**How to reproduce**

1. Go to https://asmaloney.com/software/
2. Click on download latest released (2.10.2) or latest release candidate (2.11rc1)
3. Scroll down to install it on MacOS 10.15.x (tried on 10.15.5), and try to open it

**Expected behaviour**

Software opens normally.

**Additional context**

I believe this is just missing notarisation for the app, as required now by Apple?

**Your environment**
 - CC Version (or git hash/tag): 2.10.2,  2.11rc1
 - OS & Version: MacOS 10.15.5
 - Graphics card: N/A
 - Qt Version (if compiling): N/A

**Comment by asmaloney** [comment]
Yes - this is due to Apple's security theatre.

For any applications you run into this with, you should be able to right-click the application, select "Open", and then you should have an "Open" button on the dialog.

Once you've opened it this way once, it should open fine by double-clicking it.

Note: Apple does not provide a way to notarize Open Source applications easily, and they've made it an extremely complicated process, so I'm afraid CloudCompare will likely never be notarized.

**Comment by asmaloney** [comment]
I'll take the thumbs-up as meaning it worked for you and I'll close this issue... (I won't be upgrading to 10.15, so I can't test it.)

**Comment by imrehg** [comment]
That 👍 meant that I understand your reasoning, thanks for taking the time sharing it, really appreciate it!

Unfortunately this means that our team cannot use CloudCompare due to IT security compliance requirements for our company, that doesn't allow us to bypassing Mac security settings like this. That's too bad, as we are a big fan of open source software, we use them and contribute back whenever we can, and the alternative solutions for the same task are less capable. I thought it might be useful if we give some feedback, in case it contributes to your thinking about the originally reported issue.

Cheers!

**Comment by dershow** [comment]
Andy,

I’ve tried it and yes, CloudCompare opens as expected on OS 10.15.5.  

--Adam

**Comment by dershow** [comment]
Here’s how Apple explains how you can run an app such as CloudCompare:
https://support.apple.com/en-us/HT202491 <https://support.apple.com/en-us/HT202491>

Without understanding your specific IT requirements I have no idea if following the Apple instructions is compliant.  

--Adam

**Comment by asmaloney** [comment]
@dershow Thanks - that's a good link to have for reference.

**Comment by wanfengkai** [comment]
# A work around for any of you who can not use this due to IT security limitation

Just for any of you who can not use the solution mentioned above because of IT security reason. Here is my solution.

**OS:**: Catalina, company device.

**HOW-TO**

### Install pre-requests using Homebrew:

```brew install qt```

```brew install cmake```


### Get this source code

```git clone --recursive https://github.com/cloudcompare/CloudCompare.git```

### Manually build it using cmake

**You need to cd to the project root** 

```cmake -S . -B ./build```

What you are doing here is just use source Makefile in this folder to build the application to ```./build``` folder.

### Find your ```cloudcompare.app```

If the build succeed, you should be able to find it in ``./build/qCC/CloudCompare.app``

**PS**: if you want, you can also copy it to your Application folder 

You should be able to click and open it now
![image](https://user-images.githubusercontent.com/16138109/97552013-04d8a480-19d4-11eb-9dd4-af12a214ddf9.png)

**Comment by Nivanna** [comment]
Thank you, It works !
