### ISSUE TITLE
Keep comments when loading and saving plys 

### ISSUE THREAD

**Issue by eduardoiscar** [CloudCompare/CloudCompare#1319]
**Describe the feature you would like**
When loading a ply file that includes comment fields the comments get printed in the console. After doing some modifications to the file and saving it as a new .ply, the original comments are gone and replaced by:
 _comment Created by CloudCompare v2.12 alpha
 comment Created 31.08.20 11:16._ 

I think it would be very useful if the old comments could be kept, with the new ones simply being appended to the file after saving.

**Comment by dgirardeau** [comment]
Hi,

Well, as CC handles a lot of different formats, once a cloud is loaded, not all the specifics of a particular format are kept. Especially if this information is not re-used by other formats.

**Comment by eduardoiscar** [comment]
Yes, that makes sense. It would still be very helpful, as I have pointclouds with metadata saved in the plys comment section that have to be preserved after cleaning etc.
Would adding a new member variable to ccHObject (such as std::vector<std::string>) that would get populated from the PlyFilter load and save methods be an acceptable solution?

**Comment by dgirardeau** [comment]
No, we have the concept of "meta-data" to associate a point cloud with any kind of data (you just need a unique key, and you can attach to it any type of data thanks to the QVariable interface). So you would have to same the comments as a QStringList and with a key such as "ply.comments". And then at saving time, check if the cloud has some meta-data with the 'ply.comments' key, and use them instead of the default CloudCompare one.
