### ISSUE TITLE
Old custom plugin does not load 

### ISSUE THREAD

**Issue by eduardoiscar** [CloudCompare/CloudCompare#1322]
**Issue**
Back in May I developed a little plugin for CloudCompare. I used the latest version on master at the time, and everything worked. After updating to the latest version of CloudCompare yesterday, the plugin fails to load. 
I noticed looking at the git logs that the folder structure for 3rd party plugin has changed, so I moved the plugin into a _private_ subfolder. CMake picks it up, it gets compiled without issues and the resulting .so placed in the lib/cloudcompare/plugins path in the install directory. When starting CloudCompare however I get the following error message printed in the console: _[12:52:54] 	libScanCleaner.so does not seem to be a valid plugin or it is not supported by this version_

I have spend quite a bit of time trying to figure out what changed in how plugins are loaded, but without luck. Any ideas what might be causing this?

Thanks! 

**Your environment**
 - CC Version (or git hash/tag): 5bc9f6c
 - OS & Version: Ubuntu 18.04
 - Qt Version (if compiling): 5.9.5

**Comment by tmontaigu** [comment]
Hello, I had a similar problem when updating a plugin to work with a recent version of master.
The problem was that the `Q_INTERFACES`  macro 'call' in the .h of my plugin was missing `ccPluginInterface`

see the ExamplePlugin https://github.com/CloudCompare/CloudCompare/blob/5bc9f6c43e54801b98c8927c153934a024409cb9/plugins/example/ExamplePlugin/include/ExamplePlugin.h#L43

**Comment by eduardoiscar** [comment]
That was it! Thanks a lot!
