### ISSUE TITLE
animation

### ISSUE THREAD

**Issue by ramos-3d** [CloudCompare/CloudCompare#1332]
I'm using CloudCompare 2.12.alpha... animation plugin gives error (see attached file/image)

**Comment by dgirardeau** [comment]
I don't see any attached file/image?

**Comment by ramos-3d** [comment]
![cc](https://user-images.githubusercontent.com/72264993/95070074-7daf4e00-06ff-11eb-8462-5b51bc41e060.jpg)

**Comment by ramos-3d** [comment]
Sorry, I forgot

**Comment by dgirardeau** [comment]
Ok, so the bug was actually just an issue with the version of FFMpeg library (I upgraded it for the Windows build). The latest alpha version can be downloaded from the official website: https://www.cloudcompare.org/release/CloudCompare_v2.12.alpha_setup_x64.exe

(P.S.: and the user now has the option to choose the output format/codec!)
