### ISSUE TITLE
Build with tbb 2021.1.1 fails

### ISSUE THREAD

**Issue by Mic92** [CloudCompare/CloudCompare#1385]
**Describe the bug**

Hi I am an nixpkgs maintainer and while updating [tbb](https://github.com/NixOS/nixpkgs/pull/109113), I noticed that cloudcompare is no longer compatible with tbb 2021.1.1:

**How to reproduce**

```
$ mkdir build && cd build
$ cmake ..
CMake Error at CC/cmake/FindTBB.cmake:187 (file):
  file failed to open for reading (No such file or directory):

    /nix/store/7favnqcnyys88bxgxmdw86mpf9j1dxqs-tbb-2021.1.1/include/tbb/tbb_stddef.h
Call Stack (most recent call first):
  CC/CMakeLists.txt:30 (include)

-- Found TBB: /nix/store/7favnqcnyys88bxgxmdw86mpf9j1dxqs-tbb-2021.1.1/include (found version ".")
```

**Expected behaviour**

TBB changed their header files you can use cmake file as an example: https://github.com/OpenImageDenoise/oidn/blob/master/cmake/FindTBB.cmake

**Your environment**
 - CC Version (or git hash/tag): 2.11.3
 - OS & Version: NixOS unstable
 - Graphics card: not relevant 
 - Qt Version (if compiling): not relevant

**Comment by dgirardeau** [comment]
Thanks for the feedback. I don't know if anyone is still using this option. However if anyone wants to fix it, then I guess it will help.

**Comment by Mic92** [comment]
Should I just disable this in our build than?

**Comment by dgirardeau** [comment]
Well, the impact should be limited if you remove TBB. In most of the cases we use the STL 'parallel_sort' feature if TBB is not activated. The only exception is for point picking where we rely on OpenMP. So if OpenMP is available, there won't be any noticeable impact. However, if it is no available, the point picking will be slower.

**Comment by bartoszek** [comment]
@dgirardeau If it's still relevant, the issue is related to QT `emit` colliding with the tbb `emit`. To fix simply disable the Qt emit with `CONFIG += no_keywords`
Reference: https://gitlab.kitware.com/paraview/paraview/-/issues/21323

**Comment by dgirardeau** [comment]
What's the equivalent with CMake / C++ preprocessors ? (since we don't use QMake).

**Comment by tmontaigu** [comment]
The equivalent would be
```CMake
target_compile_definitions(CloudCompare PRIVATE QT_NO_KEYWORDS)
# or
add_compile_definitions(-DQT_NO_KEYWORDS)
```
However that would disable the `slots` `signals` `emit` defined by qt in the whole program,
this may force a lot a changes to replace `slots` with `Q_SLOTS`, `emit` with `Q_EMIT`.

I had/have the same problem in my python plugin for cloudcompare. Python uses `slots` somewhere in its code,
so the Qt `slots` macro conflicts, so instead of adding the `QT_NO_KEYWORDS` in simply undef before #including the 
offending header.

```C++
#undef slots
#include <pybind11/pybind11.h>
```
and sometimes I have to redefine what I had to #undef, but it happens rarely
```C++
#define slots Q_SLOTS
#define signals Q_SIGNALS
#include <ccCommandLineInterface.h>
```

**Comment by bartoszek** [comment]
@dgirardeau Oh.. it dose, but it's a commitment on your side: I've quickly bodged a patch for, could make a PR if you like it:
https://github.com/bartoszek/AUR-cloudcompare-git/blob/master/tbb.2021.patch
Also `CCCoreLib` requires an update since `tbb:2021` no longer provides `${TARGETS_LIBRARIES}` var.
https://github.com/bartoszek/AUR-cloudcompare-git/blob/master/tbb.2021.cccorelib.patch

**Comment by dgirardeau** [comment]
Yes, looks a lot less impactful!

**Comment by dgirardeau** [comment]
@bartoszek Can you maybe open PRs? I guess we will want the patch for CCCoreLib anyway.

And for the other one... let's see ;)

**Comment by bartoszek** [comment]
Ok, just let me polish it a bit, make it look like someone cares.

**Comment by bartoszek** [comment]
Ok, it looks quite nicely and safe. I've tried @tmontaigu `#undef emit` trick but there was a bunch of interjecting dependencies so I've gave up :feelsgood:
