### ISSUE TITLE
A part of DEM ascii data is considered as invalid height

### ISSUE THREAD

**Issue by donghuny** [CloudCompare/CloudCompare#1402]
Hello,

I would like to report a case that looks weird to me. This could be a bug or my mistake.

When I opened an ascii DEM file in CC, I got a window message "This raster has pixels with invalid heights. Shall we remove them?." If say No, the height of that part (considered invalid by CC) was changed to -1.877606. When I checked the file by an editor, all numbers looked good. I could avoid this problem when I translated the height by -100 (in z) in opening it. However, there occurred another problem: invalid height somewhere else in the file (which was originally the lowest height (zero)). The height was expected to -100 because of the translation, but the value was changed to -1.877606.

I think the problem might be caused by the height of the box set by CC which is smaller than real height of the file. Please see below the screen-capture showing the problem.

![image](https://user-images.githubusercontent.com/15655081/108225915-6602c000-710a-11eb-82b9-69a05ee1b466.png).

I used version 2.12 alpha.

Thank you.

DongHun

**Comment by donghuny** [comment]
I will asked this question in the users forum.

**Comment by dgirardeau** [comment]
Oh no, it's much easier to talk about issues on github actually.

Can you share the file with me?

**Comment by donghuny** [comment]
Hello Daniel,

Thank you very much for your message.

I can send you the file. I could not send it to you by email (the compressed file size is around 9 Mb) Please let me know about how to share it with you.

Thank you!

DongHun

**Comment by dgirardeau** [comment]
Well on my side 9 Mb would work (admin [at] cloudcompare.org). But you can use wetransfer.com for instance (it's free).

**Comment by dgirardeau** [comment]
Thanks for the file. This helped me understand the issue: for a unknown reason, GDAL (the 3rd party library that loads raster files) is reporting a range of altitudes which is smaller than the actual altitudes in the file/raster. This would led CC to think that the points with altitudes outside of this range were invalid.

And due to an issue with CC's code, the altitudes of these points were already arbitrarily replaced by a constant value. Even before asking the user whether these points should be kept or not.

I've fixed this: 7dd5185d2eb2cc2340b4527d9f4a8c061d25ff23

I'll try to upload a new version of the 2.12.alpha version tomorrow.

**Comment by donghuny** [comment]
Hello Daniel,

I am glad to hear that the data helped you understand the problem.

I look forward to the new version.

Thank you!

DongHun

**Comment by dgirardeau** [comment]
The new 2.12.alpha release is online now.

Thanks for the feedback.

**Comment by donghuny** [comment]
Now I can open the file correctly. Thank you!
