### ISSUE TITLE
Using RANSAC shape detection plugin crashes the program

### ISSUE THREAD

**Issue by AnasFX** [CloudCompare/CloudCompare#1453]
**Describe the bug**
Using RANSAC shape detection plugin crashes the program

**Your environment**
 - CC Version (2.12alpha):
 - OS & Version: Win10 2004
 - Graphics card: RTX 3090

**Comment by dgirardeau** [comment]
How big is your cloud and what parameters are you using?

**Comment by AnasFX** [comment]
The file is not the problem, I tried the RANSAC shape detection in the CC 2.11.3 and it is working fine.
It crashes on CC 2.12alpha.
anyway, the file is small about 50K, and the settings are the defaults.

**Comment by dgirardeau** [comment]
Ok. I've been able to reproduce it indeed. And I fixed the issue (hopefully).

I've updated the online 2.12.alpha version.

**Comment by alexwangxiang** [comment]
I am using cloudcompare v2.12 beta on ubuntu 20.04, and I built it from source, but I encountered with the same problem. When I selected a point cloud and clicked on the ransac button, the program crashes.

**Comment by dgirardeau** [comment]
Can you share the point cloud and parameters you used? Cause I cannot reproduce this issue on my side right now.

**Comment by alexwangxiang** [comment]
@dgirardeau Cloud points: 37155, parameters for ransac plugin are shown as the following picture. 
![ransac_parameters](https://user-images.githubusercontent.com/42371271/150087186-1aca25a3-123e-4bc0-b215-97c1474aa779.png)
What's more, the cmake configuration I used is the following sentence:  
cmake -DCMAKE_BUILD_TYPE=Release -DPLUGIN_STANDARD_QPCL=ON -DPLUGIN_STANDARD_QBROOM=ON -DPLUGIN_STANDARD_QRANSAC_SD=ON -DPLUGIN_MYEXAMPLE=ON -DPLUGIN_IO_QPDAL=ON -DCCCORELIB_USE_CGAL=ON -DCMAKE_CXX_COMPILER=clang++ ..
-DPLUGIN_MYEXAMPLE is a plugin written by myself which you can ignore. It is worthwhile to notice that I used clang++ as the compiler in order to avoid errors while building with cgal library. See [I](https://github.com/CloudCompare/CloudCompare/issues/1258) for detail. I tracked through some self made checkpoints in the source code, and found that the first error occurs in src/qRANSAC_SD.cpp, line 431, cloud.calcNormals(.01f*scale),
extern/RANSAC_SD/PointCloud.cpp, line 178, kd.Build(),
extern/RANSAC_SD/GfxTL/KdTree.h, line number I don't remember, BaseType::LeaveGlobalBuildInformation(*p.first, p.second)
extern/RANSAC_SD/GfxTL/CellBBoxBuildInformationKdTreeStrategy.h, line 113 to 116, cell.SplitAxis(),
extern/RANSAC_SD/GfxTL/KdTree.h, line 62 to 70, return m_splitAxis, where I found that the program didn't initialize the private unsigned int variable m_splitAxis in class KdTreeCell.

**Comment by alexwangxiang** [comment]
@dgirardeau Good news: I deleted two options -DCCCORELIB_USE_CGAL=ON -DCMAKE_CXX_COMPILER=clang++ from the cmake sentence above, and the CloudCompare built from source can run its RANSAC plugin successfully now. Tradeoff is that, I can't use delaunay 2.5d mesh now because it relies on CGAL library that I can't build successfully without clang++ compiler.

**Comment by dgirardeau** [comment]
Wow, that's strange! But thanks for the investigation ;)

I guess the code is either not properly compiled when using clang++ or the syntax is super borderline and it's interpreted differently?! 😰
