### ISSUE TITLE
Subsampling in Commandline

### ISSUE THREAD

**Issue by jambus1986** [CloudCompare/CloudCompare#1469]
Hi there,

can you make Subsampling   scalarfield-sensitive  make available in Commandline please?

thank you,
ps. noise works already very fine in commandline, well done :)

**Comment by jambus1986** [comment]
i mean scalar field is used to define the densitiy of the subsampling...

scalar field value 0 -->  subsampling distance 0.001
scalar field value 0.5 --> subsampling distance 0.005
scalar field value 1 --> subsampling distance 0.2 
values between could be calculated linearly
for example.

or is this in commandline already possible and i only dont know how?
thx

**Comment by lorinczszabolcs** [comment]
Hi @dgirardeau !

I have just tried subsampling and I have originally 4 scalar fields in a ply file. However, it does not retain all 4 of them, only the first one. (I don't know if it is because of the subsampling or am I opening the file incorrectly)

The command I am using: cloudcompare.CloudCompare -SILENT -AUTO_SAVE OFF -O ./labeled_00051_16E.ply -C_EXPORT_FMT PLY -SS SPATIAL 0.005 -SAVE_CLOUDS FILE "try.ply" -CLEAR -CLEAR_CLOUDS

Looking forward to your response!

**Comment by dgirardeau** [comment]
The only thing we could add, is what is available via the GUI version: allowing to set a SS distance for the min scalar field value, and another SS distance for the max scalar field value (the SS distance is interpolated between the 2):
![image](https://user-images.githubusercontent.com/2735509/123538450-496c3980-d735-11eb-9a8c-e39977954dc3.png)

**Comment by Jean-Roc** [comment]
@dgirardeau yes these additional parameters would be great at disposal of the command lines

**Comment by HeadLessHUN** [comment]
available in 2.13 beta, can be closed.
