### ISSUE TITLE
Command line reading .ply file does not read all scalar fields

### ISSUE THREAD

**Issue by lorinczszabolcs** [CloudCompare/CloudCompare#1476]
**Describe the bug**
Command line reading .ply file does not read all scalar fields, only one.

**How to reproduce**

1.  Download example file https://drive.google.com/file/d/13ktNlhVmJDLPU6W9LEa_z96bNcfZtQu8/view?usp=sharing
2. Run cloudcompare.CloudCompare -SILENT -AUTO_SAVE OFF -O ./labeled_00051_16E.ply -C_EXPORT_FMT PLY -SAVE_CLOUDS FILE "trial.ply" -CLEAR -CLEAR_CLOUDS

**Expected behaviour**
Load .ply file with three scalar fields (intensity, label, padding) and save it with same scalar fields.

**Your environment**
 - CC Version (or git hash/tag): 2.11.1
 - OS & Version: Ubuntu 20.04
 - Graphics card: Nvidia Quadro RTX 6000
 - Qt Version (if compiling): -

**Additional Info**
The same file can be opened via GUI and the three scalar fields can be added via the GUI upon opening.

**Comment by dgirardeau** [comment]
Yes, just as the graphical version of CC, the command line will only load one scalar field by default (you have to manually set the 2 others as being 'scalars' in the opening dialog).

The only solution right now is to prefix the field names by 'scalar_' so that CloudCompare can automatically recognize them as scalar fields ('intensity' is already recognized as being a SF):
![image](https://user-images.githubusercontent.com/2735509/122873095-a466f080-d331-11eb-8095-98f9242f2eaf.png)

**Comment by lorinczszabolcs** [comment]
Thank you for your quick response!
