### ISSUE TITLE
Stuck at Plugin generation

### ISSUE THREAD

**Issue by eiffelbastin** [CloudCompare/CloudCompare#1514]
Sorry for asking silly(maybe) ; newbie here

I am now trying to install the standard example plugin..to learn to install a plugin so i can later make my own plugin with certain function

1. after placing all the template files in the plugin\private folder, and when I try to build with 'PLUGIN_EXAMPLE_STANTARD' = unchecked i am not getting the .sln file in the output folder
but when I generate it by keeping 'PLUGIN_EXAMPLE_STANTARD' = checked I am getting a .sln file in the output but there is an error showing up in cmake [https://drive.google.com/file/d/13JWWS-bO6jVozxdwG_S4Y3y3BAWlk4Nl/view?usp=drivesdk]

2. proceeding with the generated ExamplePlugin.sln when i open the solution in visual studio I am getting this error

C:\Users\91828\Desktop\temp\exampleplugin\ALL_BUILD.vcxproj : error : Project "" does not contain any configuration.
C:\Users\91828\Desktop\temp\exampleplugin\ZERO_CHECK.vcxproj : error : Project "" does not contain any configuration.

and there is no option to build it

screen record : https://drive.google.com/file/d/1UXq9J6yHZzg7Bpsh_6VxO4sa3K_8mxBJ/view?usp=drivesdk

**Comment by dgirardeau** [comment]
Are you sure the one you are 'activating' in CMake is your copy? Because the examples are already included in the default plugins\CMakeLists.txt file (therefore you see the projects in the 'example' folder by default.

To be sure that you are compiling the right one, can you at least rename the contents of the CMakeLists.txt in the plugin folder (follow the instructions in this file: _REPLACE ALL 'ExamplePlugin' OCCURENCES BY YOUR PLUGIN NAME_). At least this way this will make things clearer.

**Comment by dgirardeau** [comment]
And mind that you should compile the whole project (i.e. point CMake to the CloudCompare root folder). Plugins needs all the CloudCompare libraries to compile.
