### ISSUE TITLE
Running command line CloudCompare on a headless RHEL server

### ISSUE THREAD

**Issue by philwilkes** [CloudCompare/CloudCompare#1599]
I have built CloudCompare from source on a RHEL server. I would now like to run CloudCompare using the command line options. However, when I try I get:

```
QSocketNotifier: Can only be used with threads started with QThread
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, minimal, minimalegl, offscreen, vnc, webgl, xcb.

Aborted (core dumped)
```

Can I run CloudCompare without a display?

**Comment by dgirardeau** [comment]
Ah, that's the classical issue with servers that have no graphic card... CloudCompare is still a graphical application, even though you can prevent the GUI to be displayed and continue in "command line" mode.

Is there a way to have a kind of virtual display driver / remote display?

Otherwise I don't know what it would take to change CC so that it becomes a 'non graphical' application... I haven't look at that so far.

**Comment by tmontaigu** [comment]
You can try running CloudCompare throuh `xvfb-run`  https://nixdoc.net/man-pages/Linux/man1/xvfb-run.1.html

**Comment by alexmyczko** [comment]
we use it with RDP, on debian you can install xorgxrdp and xrdp to get that...
