### ISSUE TITLE
Incorrect view of trihedron axes in "Rasterize" and "Volume calculation" tool.

### ISSUE THREAD

**Issue by hackery98** [CloudCompare/CloudCompare#1605]
Hi, guys, The projection axis is inconsistent with the 3D coordinate display.
see the picture below
![图片](https://user-images.githubusercontent.com/6083117/154418658-83cabf0b-cb2e-4790-aa25-a3c7c7b53cd7.png)

**Comment by hackery98** [comment]
50e57a8a4aebfe67387550bbcf58a0d1439146d9
Is that ok?
![图片](https://user-images.githubusercontent.com/6083117/154422877-10173e8a-eb2d-4fe6-a4df-2564bc98abaa.png)

**Comment by dgirardeau** [comment]
Ah sorry, I didn't see your second message and fixed it in a more global way (and I kind of cheated :D ). I simply hide the trihedron in 2D views, as there are several tools where we use 2D views to display thins in a default (X, Y) plane: see ddbe23627cf33f1c9787dacb8dc7b02776a4eb75

**Comment by dgirardeau** [comment]
One option would be to re-activate the display of the trihedron for the Rasterize tool, and also integrate your changes. My only concern is that we will now see the orthogonal dimension 'letter', which is not super nice (but that's a minor issue).

Next time, don't hesitate to open a PR directly, so that I am sure to spot your code modifications ;)

**Comment by hackery98** [comment]
ok, I got it.  Actually, in 2D, we don't need trihedron.
I also want to hide the letters in the first time. 😊
