### ISSUE TITLE
Error opening LAS file: Attempt to create stream twice

### ISSUE THREAD

**Issue by ruslo** [CloudCompare/CloudCompare#1611]
Opening a LAS file leads to a segmentation fault. The error message, as far as I understand, is from the PDAL library: https://github.com/PDAL/PDAL/blob/2.0.1/io/LasReader.hpp#L101-L102

ZIP archive with LAS file to reproduce:  [points.zip](https://github.com/CloudCompare/CloudCompare/files/8283413/points.zip)

I'm using PDAL 2.0.1. The same configuration is working fine with CloudCompare 2.11.3.

 - CC Version (or git hash/tag): 541800c9
 - OS & Version: Ubuntu 18.04
 - Qt Version (if compiling): 5.12.9

**Comment by dgirardeau** [comment]
I've tested on Windows and I can't reproduce the issue, but with a different PDAL version. Are you able to test with a more recent version of PDAL?

**Comment by ruslo** [comment]
> Are you able to test with a more recent version of PDAL?

Yeah, it seems to work with PDAL 2.2.0.

Note that the minimum required version here is 1.6:
- https://github.com/CloudCompare/CloudCompare/blob/541800c958e52d0379d62ac6bbfecd099dc09829/plugins/core/IO/qPDALIO/CMakeLists.txt#L6

Should it be updated?

Also, as I said, CloudCompare 2.11.3 is working fine with PDAL 2.0.1.

**Comment by dgirardeau** [comment]
On my side I'm using 2.1.0, so I don't know if it works with previous versions indeed.

But when looking at what changed since version 2.11.3 in the qPDAL_IO plugin (i.e after september 2020), I don't see what could explain this PDAL error. Nothing has changed regarding the order in which PDAL methods are called, etc.

In order to decide if we increase the minimum required package version (to PDAL 2.1?), I am not against it, but I'd like to get more feedback from other users (as it may still work on their side if they have a different configuration?).

**Comment by tmontaigu** [comment]
'Obsolete' as qPDAL plugin is phased out in favor of LASZip based plugin
