### ISSUE TITLE
CSF Filter - threshold stepsize limitations

### ISSUE THREAD

**Issue by SchmidL** [CloudCompare/CloudCompare#1638]
**Describe the bug**
In the CSF Filter, the minimal classification resolution is capped at 0.1 m. So for example a threshold of 5 cm cannot be set.
Also all the other parameters are limited to a given step size of 0.1 m.
**How to reproduce**
1. Plugins > CSF Filter
2. Advanced Paramter Setting
3. Classification threshold > is capped at 0.1 m

**Expected behaviour**
Set any value between 0 - and infinity, so range is defined between [0, infinity)

**Your environment**
 - CC Version (or git hash/tag): v2.12.1 (Kyiv) 
 - OS & Version: Windows 10 Enterprise LTSC, 1809

**Comment by DavixDevelop** [comment]
This is because the `QDoubleSpinBox` widget used for `Cloth resolution` and `Classification threshold` values has its `decimals` property  (the property holds the precision of the spin box, in decimals) set to 1. It would need to be set to 15 to take full advantage of the values set in the widget's `minimum` and `maximum` properties. I changed the property to 10, quickly compiled the project, and tested it out, and it works. But the caveat is, that now for example for the `Classification threshold`, instead of just displaying `0.5` (for the default value), it now displays all the decimals (`0.5000000000`).

**Comment by dgirardeau** [comment]
So I compromised and increased the input values precision to 4 (so as to be able to input values in mm, which is probably way to high considering that the algorithm is meant to be applied on terrains and airborne clouds).

This will be available in the next 2.12.2 release (hopefully soon)

**Comment by SchmidL** [comment]
Perfect - mm is perfect. Yes the intention yes but is also a really  nice tool to clean up floor scans from any unwanted clutter around. Thank you!

**Comment by dgirardeau** [comment]
The 2.12.2 version for Windows is now online.
