### ISSUE TITLE
PDAL 2.4.0 compatibility

### ISSUE THREAD

**Issue by nh2** [CloudCompare/CloudCompare#1643]
CloudCompare currently does not seem to be compatible with PDAL 2.4.0.

The nixpkgs CI found that compilation works with PDAL 2.3.0 but not with 2.4.0, which gives a compile error (unfortunately truncated): https://github.com/NixOS/nixpkgs/pull/165972/checks?check_run_id=5723532108

It would be nice to have 2.4.0 support.

**Comment by dgirardeau** [comment]
So I tried to compile with PDAL 2.4.0, and I only had an issue with the LASFilter.cpp file (due to the usage of structures that have been moved to private parts of PDAL now).

I guess you should try to compile with the updated PDAL I/O filter in preparation: https://github.com/CloudCompare/CloudCompare/pull/1561

I don't know how far from completeness this branch is however (@tmontaigu?).

**Comment by dgirardeau** [comment]
In the branch version_2.12.2 you'll find this commit that should allow you to compile with PDAL 2.4.0:
https://github.com/CloudCompare/CloudCompare/commit/63818d5083f3d3f5fbc5d8db5655004461c95437

**Comment by tmontaigu** [comment]
> I guess you should try to compile with the updated PDAL I/O filter in preparation: #1561
> 
> I don't know how far from completeness this branch is however (@tmontaigu?).

If I remember form the last time I touched this rewrite it was in an 'alpha' state, the main functionalities were there
but they need actual testing

**Comment by HelyaHsiung** [comment]
PDAL 2.4.3 has been installed on my debian 11, then I build `CLoudCompare 2.13 alpha` and `libQPDAL_IO_PLUGIN.so` generated, but I still can't open LAS or LAZ file. It seems that `libQPDAL_IO_PLUGIN.so` doesn't take effect.

**Comment by nh2** [comment]
Closing due successful build against PDAL 2.5.4 in https://github.com/NixOS/nixpkgs/pull/215960#pullrequestreview-1450451352
