### ISSUE TITLE
Unhandled file extension ‘e57‘

### ISSUE THREAD

**Issue by runxel** [CloudCompare/CloudCompare#1665]
**Describe the bug**

**How to reproduce**

1. Double click on a .e57 file
2. Receive this error message
<img width="532" alt="grafik" src="https://user-images.githubusercontent.com/2277182/175907741-f13c7b64-fe96-4514-9911-183f2b390fb5.png">
3. The file will not open.

**Expected behaviour**
The file should open properly.

**Additional context**

**Your environment**
 - CC Version (or git hash/tag): 2.13 alpha
 - OS & Version: MacOS 64bit 
 - Graphics card: M1
 - Qt Version (if compiling): n/a

**Comment by runxel** [comment]
Hey Daniel, yes, it is in the menu and opening via the menu works fine, just as drag-and-drop.
Only the double click from the finder has these hiccups.

**Comment by dgirardeau** [comment]
Then I guess it's an issue with how parameters are passed from the command line to the file loader... Or does the file has local characters by any chance? (i.e. non latin)

**Comment by runxel** [comment]
Theoretically yeah, there could have been some German Umlauts, but no. Happens with all files. Local and remote (on NAS). Even if the file name and path has no spaces in them.

**Comment by dgirardeau** [comment]
Even with the latest 2.13.alpha version? (there was a recent improvement about this but I'm not sure if it was 100% functional on all versions of Windows)

**Comment by tmontaigu** [comment]
I tested with a .las and a .e57, when double clicking the "can't guess file format, unhandled extrension" errors appears
however drag'n drop or using File -> Open menu works

**Comment by tmontaigu** [comment]
I had a look at this, as I expected, the core of the issue is that CC tries to load the file before all the plugins have been loaded.

On macOs, when double clicking a file for which CC is set as the default app, the filepath is not passed as argument to the .app
like it does on windows (if i'm correct) but instead a QEvent is triggered.

And so, we get and handle this special QEvent before all the plugins have been initialized.

However I have not yet found a clean way to fix this

**Comment by dgirardeau** [comment]
Yep, maybe put the command received by the QEvent in a static variable that you check just after the main window has appeared?
