### ISSUE TITLE
Cloud2Mesh distance gives really different results between version v2.11 and v2.12.

### ISSUE THREAD

**Issue by andreabonvini** [CloudCompare/CloudCompare#1672]
I tried to compute the Cloud2Mesh distance between two meshes with both CloudCompare versions v2.11 and v2.12
With version v2.11 I obtain a mean distance of 0.0075 and with version v2.12 (or later) I obtain a mean distance of 0.013.
Unfortunately, I can't share the meshes for professional reasons. Did something changed between the two versions? What's the correct one?

OS: Windows 11

Thanks

**Comment by dgirardeau** [comment]
That's maybe due to this fix in CCoreLib: https://github.com/CloudCompare/CCCoreLib/commit/6bbdec65174e9e0466ceee0042134d0ec4c993d8

In which case the 2.12 version would give more accurate results.

**Comment by andreabonvini** [comment]
But actually we got _less accurate results_ with v2.12.

Specifically:

VERSION V2.11.3 ---> 8um
VERSION V2.12 alpha -->7,5um
VERSION V2.12beta ---> 13um
VERSION V2.12.3 --> 13um

**Comment by dgirardeau** [comment]
There have been 2 different commits indeed:
- one which was mostly cleanup of the code, and small computation improvements maybe (which would explain the very small delta between 2.11.3 and 2.12.alpha, especially since we maybe be close to the numerical accuracy with such small values)
- the other fix had more impact, depending on your mesh (it was a corner case, but your meshes might present this particularity)

Would you mabe able to export a small part of your meshes (you can crop it with the Cross Section tool) and check if you see the same trend? And then share it with me if it's not recognizable (admin [at] cloudcompare.org)

**Comment by andreabonvini** [comment]
Ok thanks, I think we can continue the conversation privately.

**Comment by dgirardeau** [comment]
I think there's a bug actually. I'm on it!

**Comment by dgirardeau** [comment]
Ok that's fixed! That was tricky. CC was overlooking sometimes some triangles and was instead considering a nearby triangle. This is why the differences were very small.

I've released a version 2.12.4 with the bug fix (and some others). The 2.13.alpha will also be updated accordingly.

Thanks a lot for spotting and reporting this bug!

**Comment by andreabonvini** [comment]
Great! I guess that at this point a new version of CloudComPy should be released too, right?
