### ISSUE TITLE
Issues Importing LAZ (1.4) File, possible loss of precision in XY coordinates

### ISSUE THREAD

**Issue by Marcus-Richmond** [CloudCompare/CloudCompare#1699]
Trying to import LAZ files, the files import into cc without any errors but the points show up in a straight line. It's as if the precision of the X and Y coordinates is lost or reduced. Here is a screenshot of cc right after importing one of the files: 

![image](https://user-images.githubusercontent.com/59568811/196007758-72f5ed97-35a5-48ee-81bc-1e3488bb51f0.png)

Here is a link to the download page of the dataset: https://noaa-nos-coastal-lidar-pds.s3.amazonaws.com/laz/geoid18/9629/index.html

The exact file I'm using for this example is: https://noaa-nos-coastal-lidar-pds.s3.amazonaws.com/laz/geoid18/9629/20220614_MRR22_001.copc.laz

The download page includes the note: 

> This data is LAS 1.4 format compressed using laszip in native mode. You'll need laszip version 170330 or higher (or tools compiled with at least that version of laszip) to read it.

However, reading through some of the other issues, sounds like cc should be able to handle LAS 1.4 fine?

Here is how the file looks when I open it in QGIS: 

![image](https://user-images.githubusercontent.com/59568811/196007824-a22ca772-36a8-4f93-8cc3-a2b21e663334.png)

**Your environment**
 - CC Version (or git hash/tag): Happens on both  2.13.alpha (10/15/2022) and 2.12.4 Kyiv (7/14/2022)
 - OS & Version: Windows 11

Thanks,

**Comment by dgirardeau** [comment]
I think that the issue is simply that the cloud (LAZ file) has non cartesian coordinates. X and Y are angles, while Z has metric units. CC does not handle geographic coordinate reference systems. You would have to convert them to a projected coordinate reference system first (see https://docs.qgis.org/3.22/en/docs/gentle_gis_introduction/coordinate_reference_systems.html, section 8.5).
