### ISSUE TITLE
Not possible to cancel out of multi-threaded operations

### ISSUE THREAD

**Issue by jlinBE** [CloudCompare/CloudCompare#1713]
If I press the 'cancel' button on some multithreaded operations such as opening multiple files or point-cloud registration, it seems only one thread gets stopped and the rest keep going.  the only way to stop such an operation early is to kill the cloudcompare process.

**Comment by dgirardeau** [comment]
Well, not all operations in CC are multi-threaded, and not all are using all threads/cores. For instance, when loading multiple files at once, only one thread is used. If you load multiple files by dropping them one by one, then each one will be processed by a different thread, but in this case you should see multiple progress dialogs with a 'cancel' button for each (_and that would not be a good way of loading files, since if the files are on the same drive, the different threads will compete with each other and the overall operation might take more time_).

Another thing that may happen is that while the dialog disappears (which is an automatic behavior when the "Cancel" button is clicked), it may take some time for the process/thread behind to actually stop (depending on what it's currently doing, and whether the operation can be interrupted in the middle or not). For instance, for registration (I guess it's 'ICP'?) it can typically the case if each iteration is long. The operation can only be stopped at the end of the ongoing iteration (and before jumping to the next one).
