### ISSUE TITLE
How to split a point cloud into multiple smaller ones?

### ISSUE THREAD

**Issue by isspid** [CloudCompare/CloudCompare#1769]
**Describe the feature you would like**
The possibility of splitting a point cloud into smaller ones.

**Describe alternatives you've considered**

**Is your feature request related to a problem? Please describe.**
I need to upload point clouds to another software which doesn't deal well with large files/point clouds. One solution would be to split the point cloud into smaller ones and upload them sequentially.

**Additional context**
I have searched the issues and I see that options such as tiling and splitting via the cli are mentioned but I haven't seen them in the app or documentation.

**Comment by dgirardeau** [comment]
You have basically two options: either use the 'tiling' option of the LAS import dialog/tool (but you'll need a LAS file as input).

Otherwise, you'll have to load the cloud entirely in CloudCompare, and then use the 'repeat segmentation' option of the "Cross section" tool (https://www.cloudcompare.org/doc/wiki/index.php/Cross_Section#Extract_multiple_slices.2C_envelopes_or_contours). Or the '-CROSS_SECTION' command line option.

**Comment by dgirardeau** [comment]
Well, you can create a scalar field with all point indexes (Edit > Scalar fields > Add point indexes as SF). And then segment the cloud based on these values (Edit > Scalar fields > Filter by value, etc.).
