### ISSUE TITLE
Is it possible to merge a mesh and point cloud into a single model.

### ISSUE THREAD

**Issue by vipasyan** [CloudCompare/CloudCompare#1779]
I have read two point clouds can be merged and a level of detail (LOD) can be applied, so at a particular camera position more points are displayed and at other camera positions, fewer points are displayed in the same model.

I want to merge a mesh and point cloud into a single model (.ply) and apply the above concept so that at a particular camera position mesh is displayed and at another camera position (far away from the viewer) point cloud is displayed.

Is there any available code which performs the above operation? please let me know.

Thanks in advance.

**Comment by dgirardeau** [comment]
Well, in CloudCompare you can indeed merge points clouds (but not a mesh and cloud, or at least you'll need to convert the mesh to a point cloud).

And then, above a given number of points, CC will compute the octree and use a LoD strategy to display points in a progressive (and hopefully) smart way. See the ccPointCloudLOD class (https://github.com/CloudCompare/CloudCompare/blob/master/libs/qCC_db/include/ccPointCloudLOD.h). But let me warn you that the way this is done in CloudCompare is not conventional, and maybe not optimal (due to the very specific octree structure we use).
