### ISSUE TITLE
gps_time precision loss when reading/writing LAS files

### ISSUE THREAD

**Issue by p-leroy** [CloudCompare/CloudCompare#1860]
This one is related to a closed PR: "Loss of accuracy when calculating the GPS time shift. #1798"

When you open a LAS file with qLASIO, the GPS time is not stored in its native format (64 bits) but in 32 bits with a shift. This leads to a loss of accuracy which could be a problem for people who need to modify a LAS file keeping the precision of the GPS time when saving the outputs (this is my case ;-)).

Maybe we could propose an option to read the GPS time as doubles when opening a LAS file with a warning on memory usage?

**Comment by dgirardeau** [comment]
So in addition to the GPS time shift option that was added to the LAS dialog a while ago, there's now a new version of CC that will natively handle large/double values in all scalar fields. This deprecates the need for scalar field Global Shift, and it makes things much simpler for the users of course.

The branch is here: https://github.com/CloudCompare/CloudCompare/tree/double_sf

I'm just waiting for Thomas and/or Romain to fix the Python plugin, because this new concept broke something there 😅 

And you can of course compile it on your side, or test it here: https://www.cloudcompare.org/release/CloudCompare_v2.14.alpha%20%2811-17-2024%29_setup_x64.exe

**Comment by p-leroy** [comment]
Thank you, it is a really nice new feature!
