### ISSUE TITLE
Pcd file doesn't exist when opening pcd file

### ISSUE THREAD

**Issue by lizhengsi** [CloudCompare/CloudCompare#1969]
**Describe the bug**
Open pcd file failed, and it pointed out that pcd file doesn't exist! As the picture show:
![image](https://github.com/CloudCompare/CloudCompare/assets/18499731/4b119753-ed0a-4d12-889b-f72712ec170d)
![image](https://github.com/CloudCompare/CloudCompare/assets/18499731/10417b06-17c4-4022-b950-d597b3b468b7)

**Comment by rjanvier** [comment]
Hi. Are you using the flatpack package?

**Comment by lizhengsi** [comment]
Yes. The current path of pcd file is not supported by the software, but it worked when i changeed the path, just like "/home/user/0.pcd"...

**Comment by rjanvier** [comment]
/mnt path is not accessible by default via Flatpak, you have to explicitly grant permission to the Flatpak application. You can do it by using the command line or something like [flatseal](https://flathub.org/apps/com.github.tchx84.Flatseal).
Also, now you can switch to the master channel of the Flatpak, since it contains the final 2.13 release from released two weeks ago.

**Comment by lizhengsi** [comment]
Thanks! 
I installed [flatseal](https://flathub.org/apps/com.github.tchx84.Flatseal) which you recommended and add `/mnt` path under `Filesystem` option in flatseal, finally it works!
