### ISSUE TITLE
Dot Product .dp file, crash on load

### ISSUE THREAD

**Issue by whitej1** [CloudCompare/CloudCompare#1973]
Attempting to open Dot Product *.dp file, and cloudcompare crashes. Have tried with multiple files, all with same results.

**How to reproduce**
1. File, Open
2. select *.dp file

**Your environment**
 - CC Version (or git hash/tag): 2.13.0
 - OS & Version: Windows 11 Home, 23H2
 - Graphics card: NVIDIA GeForce RTX 3080
 - Qt Version (if compiling): 

I have confirmed that this is not an issue with CC 2.6.3

**Comment by dgirardeau** [comment]
Hello,

I can't reproduce the issue on my side. Can you share a sample with me maybe? (to admin@cloudcompare.org)

**Comment by dgirardeau** [comment]
Ok so I can reproduce the issue, and it seems very particular to this file. As soon as a second frame is read, it will make CC crash (even if it's from a second file that works otherwise). It seems that your file causes a corruption of the DP DLL. I've contacted the DotProduct team so that they can have a look on their side.

**Comment by dgirardeau** [comment]
So with the help of the DotProduct team, we've identified that it was an issue with an older SDK. Updating the SDK to the latest version seems to fix the issue. We will soon release version 2.13.1 with this fix. I'll try to post a link to a preview version if it takes too much time.

**Comment by dgirardeau** [comment]
See the 2.13.1.preview version: https://www.cloudcompare.org/release/CloudCompare_v2.13.1.preview_setup_x64.exe

**Comment by whitej1** [comment]
Great. Works perfectly. Thank you.
