### ISSUE TITLE
Point list picking for mesh faces

### ISSUE THREAD

**Issue by eimix** [CloudCompare/CloudCompare#20]
Now it works for points only.
It would be greate to have posibility to select face (point on center of the triangle)

**Comment by greenbrettmichael** [comment]
looking into this as I have triangle triangle (does cloudcompare allow non-triangle faces?) geodesic lying around, is adding another mode and button to ccPointPropertiesDlg acceptable? or should it work implicitly with POINT_POINT_DISTANCE mode (negative performance implications on point case)

**Comment by greenbrettmichael** [comment]
I have a geodesic algorithm for triangles :white_check_mark:
I have getting the triangle from `ccPointProperiesDlg` :white_check_mark:
I am fighting against how points are processed :x:

Currently points are fed into the label `cc2DLabel* m_label;` owned by `ccPointPropertiesDlg` to create `cc2DViewportLabel* m_rect2DLabel;`. `cc2DLabel` is very specialized for handling point data (see LabelInfox structs), and so extending it to support triangle input doesn't make sense. :thought_balloon:
It would be possible to one-off store back to back triangle data (or mixed triangle/point) on `ccPointPropertiesDlg` with a new private member, but this would likely require a new `ccPointPropertiesDlg::Mode` be created to support the use of it. If this action is a taken, another button would need to be added as well.

@eimix  suggests using the center of the triangle, this is really low hanging fruit with none of these problems and could be PR'd right now. However, with large triangles this will be very inaccurate with triangles larger than the desired precision. A counter point though, is that there is still value in a rough measurement tool, if you cared about farthest or closest point between surfaces you would likely not be hand selecting the point or triangle. :low_brightness:

I am interested in getting an opinion on action from @dgirardeau who labeled this as an enhancement for guidance on which way this should be implemented or none of the above.

**Comment by dgirardeau** [comment]
I would personally create a new kind of Label? Like a cc2DTriangleLabel? (and rename the former cc2DLabel class cc2DPointLabel?). At least this is what I would do for the standard picking mechanism (ccGLWindow::startPicking) instead of create a 3-points label as it is currently done.

Do you need me to create this class?

Otherwise if I remember well (but I made this choice a long time ago), I wanted to be able to pick the triangle in wireframe mode even though its interior is not actually displayed (as the current 'GPU' based picking is actually handled by the driver - and not the GPU - and it relies on the picking buffer which does not work if no pixel is drawn). This is why I forced the CPU-based method.

**Comment by jfbourdon** [comment]
I can't directly help implementing this feature, but I would definitely use it if it was available. CC is more about point cloud than mesh, but for what I do, I find it easier and faster to use than MeshLab for exemple.

The OP suggested the possibility to select a face by the center of the triangle, but it would be even better if it could be from anywhere on the triangle. That behing said, if selecting by the center of the triangle is an easy solution, it would still be useful feature to start with. Also, if I understand correctly, it would then enable a point list picking without having to show/activate the point cloud.

**Comment by dgirardeau** [comment]
Ok I updated CC so as to be able to pick points on triangles. I upgraded the cc2DLabel entity so that it can handle both points from clouds and points from meshes (with barycentric coordinates).

Now the Point Picking tool and the Point List Picking tool can both be used directly on meshes!

See 4d09c63d709daed9a6bee38cdf76d3b239aa79b9.

I'll upload the new 2.11.alpha version soon.

**Comment by dgirardeau** [comment]
The Windows version is now online ;)
