### ISSUE TITLE
Riegl format RXP raw laser scanner data

### ISSUE THREAD

**Issue by wex215** [CloudCompare/CloudCompare#2001]
Hi.
I would like to know if there will be an update of Riegl formats in this application.
The extension that interests you is the RXP format. 
Uploading data directly from the scanner to this CloudCompare software package.
Maybe there are any file converters from the Riegl device for uploading to the CloudCompare software package.

**Comment by dgirardeau** [comment]
@NeroBurner

**Comment by NeroBurner** [comment]
No immediate interest from my side. But I'd be happy to review a PR writing an RXP plugin.

RXP Format has no MTA resolution, so everything will be in the first MTA Zone.
I need to check if there is a RXP SDK publicly available like for the RDB-SDK (but I don't think it is). Otherwise it would be impossible to integrate into the flatpak.

But viewing code should be possible I think. You'd have to get the rxp SDK yourself and compile the plugin

**Comment by NeroBurner** [comment]
A quick web search shows the SDK is called RiVLib.

The only download I've found is in the members area of RIEGL website

http://www.riegl.com/index.php?id=224

**Comment by NeroBurner** [comment]
@dgirardeau I think this could be closed due to lack of response/inactivity
