### ISSUE TITLE
PCD export doesn't transform point data before writing to file

### ISSUE THREAD

**Issue by karlHolmquist** [CloudCompare/CloudCompare#2015]
**Describe the bug**

After registering two clouds using the ICP-tool in CC, the transform does not appear to be applied to the point data before exporting to pcd.
However, the error is invisible inside of CC since the viewpoint is changed in the pcd file so the cloud looks transformed when opening inside of CC. 

**How to reproduce**

1. Open two point clouds,
2. Use the registration tool to register the cloud
3. Save the transformed cloud as a pcd file
4. Open the pcd in an external program
5. Notice that the point positions are still the same as originally, e.g. not transformed but the viewpoint field has been changed

**Expected behaviour**

The point data should be transformed before saving to file, not relying on the VIEWPOINT field for storing the transform

**Additional context**

The problem can be avoided by manually deleting the sensor object of the point cloud before saving, probably forcing a transform of the point data

**Your environment**
 - CC Version (or git hash/tag): v2.13.1 from Flatpak repo
 - OS & Version: Ubuntu 20.04.6 LTS
 - Graphics card: Nvidia RTX 3070
 - Qt Version (if compiling):

**Comment by dgirardeau** [comment]
So I've finally had the time to look into this. There have been a lot of back and forth on this, apparently depending on users views on what the VIEWPOINT should be used for...

Currently, CC loads both the VIEWPOINT information and the raw cloud coordinates. Then it automatically applies the VIEWPOINT position to the raw coordinates (= it transforms the coordinates) so that the cloud can be visualized and edited in the world coordinates, and not in the scanner coordinates.

If the cloud is transformed and saved, we only update the VIEWPOINT so as to keep the raw scanner coordinates as is. Which kind of makes sense to me.

And indeed, if you remove the viewport associated to the cloud, then CC assumes there's no scanner/world difference, and then it saves the transformed coordinates (with a default 'identity' VIEWPOINT).

I fear that changing that again will make some other users unhappy. I guess the only way to manage this difference of views would be to add a dialog... I can add to the TODO list.

**Comment by dgirardeau** [comment]
We had that in the past, but it was not 'complete' enough apparently, and harder to maintain. So we preferred to rely on PCL directly as it made more sense and it's a dependency anyway.

**Comment by motto85** [comment]
Hello all, to add to this: If you use a transform matrix to flip the cloud (e.g. by using a -1 entry), the issue leads to the PCD not even being loaded correctly inside of CloudCompare itself.

**Comment by dgirardeau** [comment]
Ah, thanks to a similar issue reported on the E57 export, I was able to understand the issue: the PCD format save the sensor pose as a quaternion. And quaternions cannot represent 'reflections' (what you obtain by multiplying only one dimension by -1).

I've fixed the way we export E57 and PCD files in this case. The only watchout is that the sensor pose is not the one you might expect in this case. A warning is displayed in the console to warn the user.

You can test that with the latest 2.14.alpha version (for Windows)

**Comment by motto85** [comment]
Thank you very much! Would it perhaps be a solution to not only display a warning, but potentially something like "Unfortunately the transformations you applied cannot be represented by the PCD format. Would you like to store the points in their transformed state and lose the transformation information?"

Because the alternative would be to have an incorrect sensor pose, which is arguably worse than having no pose at all.

**Comment by dgirardeau** [comment]
Ah, good suggestion. However, it's a bit tricky as this happens inside an I/O plugin that can be used in command line mode as well... I'll see what I can do.

**Comment by dgirardeau** [comment]
Or as your question implied, it's maybe always safer to not use the sensor pose anymore and only use the transformed points. This way CC will behave in a consistent manner in all modes.

**Comment by dgirardeau** [comment]
Okay, sorry for the noise. After looking at what was done in the E57 and PCD filters, I realize that not applying any sensor pose would probably be a greater issue, as:
- we loose the sensor main orientation which is very interesting to orient normals and do similar operations
- we loose the Global Shift (large coordinates offset) information

So for now I prefer to use a counter-reflected sensor pose than nothing (and also, we are going to change the sensor pose and the points coordinates anyway, so I don't really know which one is worse!).

**Comment by motto85** [comment]
Okay, thank you very much for all the thought you put into this issue.

Perhaps one more thought: Could this be a global option / switch to choose that the pose is never stored (and the point clouds are always transformed)? But that would of course be tricky with the CLI (unless there's a switch for the CLI that can be passed?).

**Comment by dgirardeau** [comment]
Yes, global options don't currently work with the CLI part... But one could also add such an option also to the command line of course. Overall quite a lot of work for something that doesn't look that common... But once again, this is an open-source tool, and anyone can do the change.

This issue is closed, but feel free to open a new enhancement 'issue' specific to this proposed change if you want to keep it visible.
