### ISSUE TITLE
German umlauts cause "error occurred with third-party library in charge of saving/loading"

### ISSUE THREAD

**Issue by harrandt** [CloudCompare/CloudCompare#2024]
A co-worker (!) of mine stored some points clouds in *.pcd format in folders with German umlaut stuff (ß, ä).
Well, he's young and didn't know any better. 😉
When trying to load the point clouds there are error messages. I tried to reproduce it, it does not matter if the
characters are in the file or folder name.

In file name:
![grafik](https://github.com/CloudCompare/CloudCompare/assets/116627373/4aea994f-5930-4d53-af84-49716b53abec)

In folder name:
![grafik](https://github.com/CloudCompare/CloudCompare/assets/116627373/532781cb-ab89-4195-aced-72b340bf9db2)

We can work around that, but the message was not really helpful :)

**Environment**
 - CC Version (or git hash/tag): 2.13.1
 - OS & Version: Windows 10

**Comment by dgirardeau** [comment]
Yes, I believe it's a limitation due to the fact that PCL (the library that we use to load PCD files) doesn't take wide char strings as input, but only plain ascii ones... Not sure how to improve this (unless there's another way to set the input filename with PCL).

**Comment by harrandt** [comment]
How about checking the path for the characters and displaying a simple popup: "Due to a limitation with a third-party lib we can't... blablabla" :)

**Comment by dgirardeau** [comment]
Ok, so I've looked at the PCL interface, and it was actually possible to a binary or ascii stream instead of a filename. This allowed me to load or save the files even with local characters. Hopefully it shouldn't break anything...

You can test this with the 2.13.2 preview version: https://www.cloudcompare.org/release/CloudCompare_v2.13.2.preview_setup_x64.exe
