### ISSUE TITLE
Problems with segmentation in Mac OS

### ISSUE THREAD

**Issue by stephaniewxk** [CloudCompare/CloudCompare#398]
When using the segmentation tool in Mac OS system with Retina display, the chosen polygon doesn't segment the right position no matter how I change the viewing projection mode. It always has a offset from the original position.
<img width="1280" alt="screen shot 2016-06-03 at 10 50 58" src="https://cloud.githubusercontent.com/assets/19727841/15775346/4ffd2580-2979-11e6-8a6d-145bf33bd567.png">
<img width="1280" alt="screen shot 2016-06-03 at 10 51 03" src="https://cloud.githubusercontent.com/assets/19727841/15775347/575d6de4-2979-11e6-8bb2-f1204c872f82.png">

**Comment by dgirardeau** [comment]
Thanks for the feedback!

**Comment by mankoff** [comment]
I can't segment a point cloud, only a mesh. When I try to segment, the error is:

    No segmentable entity in active window! [OK]

I'm not sure if I should be able to segment a cloud, or only the mesh. If I segment the mesh, the `mesh.part` contains the mesh and points that I segmented out, and nothing else. The `mesh.remaining` is the in part only, but the vertices under that mesh contain all original vertices.

**Comment by dgirardeau** [comment]
Is the point cloud you are trying to segment the set of vertices of a mesh? If yes, then you can't indeed segment it directly (as it would 'break' the mesh structure). But you can simply clone the set of vertices and then segment the cloned version (which will become an independent cloud).

Otherwise it would be a very strange glitch?!

And for the other glitch, yes it's a known limitation (we don't bother to segment the vertices set as it would be much more complicated... and it seemd ok because CC is not really a meshing tool and at least it doesn't change the mesh part - only the output file size :D).

Mind also that the segmentation tool doesn't remesh the triangles falling over the boundary. However the clipping-box (cross section tool) does (and I believe it also takes care of the remaining vertices properly).

**Comment by mankoff** [comment]
Yes the the cloud are the vertices of a mesh. I see now why I can't and shouldn't be able to segment those vertices, unless I separate them from the mesh. If you're aware of the other glitch, then that is fine with me. This issue can probably be closed because the original `retina hell` bug seems to be fixed.
