### ISSUE TITLE
Are closed source modules allowed

### ISSUE THREAD

**Issue by NeroBurner** [CloudCompare/CloudCompare#429]
Am I allowed to distribute modules linking to proprietary libraries? I am not sure under what License the modules have to be (GPL, LGPL, any?). With LGPL I am allowed to link to proprietary libraries, but with GPL everything must be GPL if I understand it right.
In the most extreme way, is it allowed to only distribute a module as binary?

**Comment by cloudcompare** [comment]
It's true that theoretically all components should be GPL (or at least GPL-compliant).

But in effect, for plugins (**and I talk only for the CloudCompare project**) you can do whatever you want. Mostly because we decided to accept this right from the start of the project. Several plugins of the Windows version of CloudCompare do use closed source libraries (mostly for proprietary file formats using closed source SDKs) or are closed source themselves (e.g. Canupo and M3C2, even though it's temporary and they will eventually become open source).

In the more general case, plugins are in a kind of grey area regarding the GPL license (as whether they should be GPL or not depends on how independent they are from the main application).

P.S.: of course you must respect the GPL license when distributing CloudCompare itself and the other plugins.
