### ISSUE TITLE
Error PLY file in PCL  1.8

### ISSUE THREAD

**Issue by FlowzZz** [CloudCompare/CloudCompare#492]
## Current Behavior
When reading a PLY file generated with CloudCompare in PCL 1.8, the function abort because of the header line "obj_info Generated by CloudCompare!" which seems to be not supported.
## Expected Behavior
If this line is removed from the header, the file is read without any problem.

**Comment by dgirardeau** [comment]
Hum, wouldn't the bug report should be made on PCL's side?

**Comment by FlowzZz** [comment]
Yes maybe. As I lose lot of time with this bug, I prefer to inform CloudCompare users as well.

**Comment by dgirardeau** [comment]
Thanks for them. But I doubt we will change it in the standard version. This really looks like a PCL bug (_obj_info_ is part of the PLY specifications).

**Comment by asmaloney** [comment]
Yes - PCL should probably read the _obj_info_ field properly.

If you report it to the PCL developers you can point at Greg Turk's reference PLY reader/writer here:

http://paulbourke.net/dataformats/ply/plytest.c

(He's the guy who created the format.)

**Comment by dbworth** [comment]
This issue is closed, but I wanted to add some information to assist other people that are using PCL (PointCloud Library).  
PCL uses an older version of the VTK library to read .ply files, amongst other formats.  
The .ply reader it's using is out of date, and refuses to open .ply files that contain fields that it's not expecting. Instead of simply ignoring these fields, it crashes!

Heres 2 solutions to get your work done:  
 - Save the .ply file with CloudCompare, open it in Meshlab and re-save as a .ply file. ASCII or binary both work, from what I recall. If ASCII format, you can compare the difference in the fields. Then PCL is happy to open the .ply file saved by Meshlab.  
 - Use a 3rd party C++ library for reading mesh files. There's lots of them. You can even just use the newest version of VTK, version 7. Or here's a nice new module specifically for reading .ply files: https://github.com/ddiakopoulos/tinyply
