### ISSUE TITLE
Option for building with system installed shapelib

### ISSUE THREAD

**Issue by hroncok** [CloudCompare/CloudCompare#497]
Hi. I'd like to build CloudCompare 2.8.0 with shapelib installed on my system, i.e. not the one from `contrib`.

I've managed to do it this way:

```
sed -i 's/add_subdirectory.*//' contrib/ShapeLibSupport.cmake
sed -i 's/ SHAPELIB / shp /g' plugins/qFacets/CMakeLists.txt contrib/ShapeLibSupport.cmake
```

However, it feels a bit hacky. I was thinking I'd add a new cmake option, something like this:

```cmake
OPTION( OPTION_USE_SYSTEMS_SHAPE_LIB "Build with system installed ShapeLib" OFF )
```

Would you accept a pull request adding this?

(I'm trying to package CloudCompare for Fedora, so this is not a one time build, hence I'm looking for more permanent solution.)

**Comment by asmaloney** [comment]
I don't have final say, but I think its a reasonable thing to include in the cmake process (probably for both libs we include the source for). (Though I'd call it `OPTION_SYSTEM_SHAPE_LIB`.)

However... the shapelib that's included in the CC source is the version that has been used for testing, so _caveat emptor_.

Just curious - why do you need the system's shapelib? I see there's a 1.4 now available whereas we include 1.3 - does it provide fixes for something in particular that you need? We can _probably_ update to 1.4 in 2.9.

**Comment by hroncok** [comment]
As a Fedora packager, it's my responsibility to try to use the systems libs as much as possible, while bundling libraries is possible, it should be the last option.

If the system's shapelib will cause trouble, I can always switch the option back.

**Comment by asmaloney** [comment]
Ok - thanks for the info. My take on it is that doing this on principle doesn't make a lot of sense in this case since it's going to be statically linked in anyways. So best case scenario you don't actually gain anything and worst case scenario you introduce errors by linking to an unknown version of the library.

My two centimes - I leave the decision to you and Daniel :-)

**Comment by hroncok** [comment]
> since it's going to be statically linked in anyways

No. It's dynamic against `libshp.so.1`.

**Comment by hroncok** [comment]
However, if you (upstream) would have very strong opinion against this, it would be possible to keep as it is.

**Comment by asmaloney** [comment]
Nope - just my opinion. Not a strong one :-)

**Comment by dgirardeau** [comment]
I have personally no issue with this, especially if it's under the form of a new option (e.g. `OPTION_SYSTEM_SHAPE_LIB` as suggested Andy). I'll let you do a PR.

**Comment by hroncok** [comment]
I will eventually get back to this, it's still in my TODO, but that TODO is getting somehow long :D 

Hope to do it this month.

**Comment by asmaloney** [comment]
If you're poking around the cmake stuff and see ways to improve it please don't hesitate :-)

We don't have a cmake expert to lean on.

**Comment by hroncok** [comment]
I don't count as an expert either :)

**Comment by asmaloney** [comment]
It looks like I added a solution for this in 6e3606fd2ea3b42138b731897b212b158e82e94b to mirror what we do with the DXF one.

You can set `SHAPELIB_LIB_DIR` and it will use that instead of the included one. I did not include a fancy _find_package_ or anything, so it would have to be set manually.

Better late than never I suppose :-)

**Comment by hroncok** [comment]
Awesome, thanks.
