### ISSUE TITLE
Has Oculus references with Oculus option turned off in cmake

### ISSUE THREAD

**Issue by EpicWink** [CloudCompare/CloudCompare#525]
## Current Behavior
Build fails on compiling libs/qCC_glWindow/ccGLWindow.cpp:1468: 's_ocolus' not defined
Shouldn't be doing this as CC_GL_WINDOW_USE_QWINDOW should be not defined right?

## Expected Behavior
Successful build

## Steps to Reproduce (for bugs)
configure with environment below
cmake options: WILL BE POSTED SOON (but OPTION_USE_OCULUS_SDK was definitely turned off)

## Context/Comments
commenting out lines 1466 to 1472 seemed to allow me to compile

## Your Environment
* OS & Version: Ubuntu 17.04
* CC Version: release 2.8.1
* Libs gotten: PCL 1.8, ffmpeg, Qt5.8, cmake 3.7.2, CGAL, OpenMP,

**Comment by dgirardeau** [comment]
The 's_oculus' member should only be defined if the OPTION_USE_OCULUS_SDK is enabled (moreover by default it should be disabled).

There's an associated option named 'OPTION_GL_QUAD_BUFFER_SUPPORT' that should only be enabled if the previous one is enabled (otherwise it's useless).

Is any of those options enabled on your side maybe?

**Comment by EpicWink** [comment]
I’m fairly sure I had 'OPTION_GL_QUAD_BUFFER_SUPPORT' enabled, but I’ve had to can the install of Ubuntu due to Qt issues: I was never able to get the full cmake config since the above post.

Laurie
