### ISSUE TITLE
cc local builld with qt 5.9.1 crash at startup

### ISSUE THREAD

**Issue by renc** [CloudCompare/CloudCompare#567]
## Current Behavior
I have clone the cc repo to do a local build, after update to qt 5.9.1, the build success, however it crash when launching the cc, debug and release version both crash, at 
ccGLWindow.cpp, line 2468, case LOWER_LEFT_MESSAGE: renderText(10, ll_currentHeight, it->message, m_font);
it actually crash inside the renderText() function. A workaround is to comment out this function, then cc can start up.
To build with qt 5.8.0 does not have this issue.

## Your Environment
Lenovo Thinkpad T450s
* OS & Version: windows 10
* CC Version: the latest code from github
* Graphics card:  Intel HD Graphics 5500, NVIDIA GeForce 940M.

**Comment by asmaloney** [comment]
Thanks - this is #543. Commenting it out means you won't get any text displayed in the window.

What's the exact hash of the commit your branch is on?

I put in an attempted workaround in f3c6b229 that works on macOS. @dgirardeau confirmed it worked on Windows for him, but maybe we need to adjust it a little?

(As I mentioned in that other issue, this is a Qt bug that is supposed to be fixed in Qt 5.9.2 - https://codereview.qt-project.org/#/c/199820/.)

**Comment by renc** [comment]
Thank you very much @asmaloney , yes, the exact same issue. I sync your commit and that fix it. big thx!!
so maybe we can mark this one duplicated or closed.

**Comment by asmaloney** [comment]
Ok, great. Thanks for the report.
