### ISSUE TITLE
Error in new command line -VOLUME command

### ISSUE THREAD

**Issue by frar** [CloudCompare/CloudCompare#610]
## Current Behavior

I'm launching it through the following command line command:
cloudcompare.CloudCompare -SILENT -o ./pc_1.las -o ./pc_2.las -VOLUME -GRID_STEP 1.0
At the end of the computation a "Segmentation fault (core dumped)" error appears and the calculation in the Report text file is not the same obtained using the graphical user interface (through Tools-> Volume -> Compute 2.5D Volume); it is wrong because I have tried with simple las files for which I already know which could be the result (with gui the result is correct using the same parameters). IN particular the results are lower than those expected as if the calculation was not finished correctly.

## Expected Behavior

The results should be the same resulting from computation using the gui with the same parameters.

## Steps to Reproduce (for bugs)

Launch the command through the following command:
cloudcompare.CloudCompare -SILENT -o ./pc_1.las -o ./pc_2.las -VOLUME -GRID_STEP 1.0
Launche the same computation with gui using the same parameters and volume measures results are not the same.

## Your Environment

* OS & Version: I've tried it both on Linux Ubuntu 16.04 and Windos 10.
* CC Version: 2.9 beta (the only version supporting the option from command line.
* Graphics card: NVIDIA Quadro (it doesn't seem an error related to video card)

**Comment by dgirardeau** [comment]
Okay I reproduced what must be the same issue on your side: I used two LAS files, that have the same coordinates, but one has a null 'internal shift', while the other has a big 'internal shift' (I speak about the LAS files 'shift' that is used internally to avoid losing precision when dealing with big coordinates - it's equivalent to CC's Global Shift mechanism).

By default, if the user doesn't specify anything in the command line, CC uses this 'LAS shift' as 'Global shift'. Therefore in my case one cloud was loaded without any shift, and the other is loaded with a big shift. As a result one cloud had very big local coordinates, while the other had very small local coordinates. This resulted in a huge grid (something like several millions by several millions cells), that could cause a core dump or equivalent due to the memory shortage.

I changed the default behavior of CC so that no shift is applied at all when loading LAS files if the user hasn't specified anything. This should avoid such issues. **However, one should always specify what the global shift should be (either 'AUTO' or a specific value) to avoid losing precision**.

I'll also add some warnings if the grid is too big, however they will only be visible in non-silent mode.
