### ISSUE TITLE
Allow to define output file name in command line mode

### ISSUE THREAD

**Issue by alexbruy** [CloudCompare/CloudCompare#659]
It would be very nice to be able specify output file name and location, instead of creating files with harcdoded names in the current directory. This is especially useful for scripting and batch processing.

**Comment by dgirardeau** [comment]
Actually this feature is already in the TODO list for a long time. It would be good to find someone motivated by this task ;)

**Comment by Salink** [comment]
I can add this. Can I add an optional arg -S to SAVE_CLOUDS and SAVE_MESHES? Are there other commands that save results?

**Comment by asmaloney** [comment]
Normally output files are specified with "-o" on a command line. Unless there's something different here I would recommend that. If there are multiple possible outputs, then maybe "-o" with something appended to indicate what it is?

**Comment by Salink** [comment]
It looks like -o is open. I figure -s for save.

**Comment by asmaloney** [comment]
Oh that's terrible. Bad @dgirardeau!

The file you're operating on doesn't usually have a flag associated with it - it falls at the end of the command as the operand.

Command lines have a very long history of using "-o" for output files (pretty much since the beginning). It's what any POSIX-y person would expect.

So normally you would have something like:

`foo -o outputFile [file]`

**Comment by Salink** [comment]
I agree and would prefer to use -o, but I can't in this case.

**Comment by Salink** [comment]
Would something like -SAVE_CLOUDS FILE:'filename1','filename2' work?
