### ISSUE TITLE
Measure Mesh Vertices

### ISSUE THREAD

**Issue by rukie** [CloudCompare/CloudCompare#664]
I'm using Cloud Compare Version 2.10 alpha (Compiled MSVC 1910 and Qt 5.9.3)

Maybe I'm an idiot but I can't figure out how to measure the size of triangles in a mesh. The point picker doesn't let me select Mesh Verticies. 

After generating a mesh, I'd like to figure out what my mesh resolution is.
If I'm a simpleton, let me know. Otherwise, this could be a useful feature!

**Comment by dgirardeau** [comment]
Indeed, CloudCompare is primarily a cloud processing tool, not a meshing one ;)

You can get the mean triangle surface by measuring the total surface (with Edit > Mesh > Measure surface) and then dividing by the number of triangles.

Otherwise you can compute the density of the vertices set (select the 'vertices' cloud below the mesh entity and then use 'Tools > Others > Density).
