### ISSUE TITLE
Selecting Multiple Items and Attempting to change Global Shift/Scale causes Crash Win 7.

### ISSUE THREAD

**Issue by Dbhericks** [CloudCompare/CloudCompare#758]
## Current Behavior
I am trying to change the Global Shift/Scale of all objects in a file. When I select multiple Point clouds/objects under different folders and go to Edit>Edit Global Shift and Scale...  (which is NOT grayed out) CC Crashes.

## Context/Comments
(See other comment on other issue Global Shift Scale enhancement that might make this unnecessary)
Trying to insert open existing *.BIN files into existing workspace that have different saved Global Shift/Scales.  To avoid having to Transform I am trying to first open one of the 2  BIN files and trying to select all objects and change the Global Shift/Scale for all of them (so I don't have to do it for every item).

This could all be avoided if the Global Shift/Scale dialog is opened when a existing BIN file is opened into a new active workspace. If so, the  Shift/Scale of workspace (which should auto populate to the dropdown.) can be applied to the file being opened (rather than automatically applying shift scale from last time the BIN was saved...putting it into the wrong place

* CC Version: 2.9.1 Stereo 64 Bit
* OS & Version:  Win 7 Enterprise   6.1.7601 SP1 Build 7601
* Graphics card: Nvidia Quadro M1000M

**Comment by dgirardeau** [comment]
I can't reproduce your issue on my side. Have you tried with the latest 2.10 version by any chance? What kind of entities are you loading (points/mehses/other?). Do they all have the same global shift, or different ones? etc.

Otherwise no 'Global Shift & Scale' dialog is displayed by CC when loading a BIN file for several reasons:
- the user should already have seen the dialog once (and set the right Global Shift) when loading the original file. Hence we don't want to bother him/her again as in most cases it's not of interest anymore.
- the BIN file is a serialized file that stores the points coordinates as they are represented in memory. Therefore the cloud structures are loaded by block, very fast, without parsing each point independently (which would take more time). Changing the Global Shift at this time would make the loading procedure more complicated and slower
- one can still change the Global Shift afterwards with the dedicated dialog (as you tried to do - and normally it shouldn't crash ;).

**Comment by Dbhericks** [comment]
I will try on different computer with ver 2.10.
BIN files have many different objects pointclouds >10M points, meshes, viewports, labels,

See other email on How Global Shift and Scale is handled which is the bigger issue here.

David B Hericks, PMP
Principal Oceanographer/ Hydrographer
Hydrography/Geophysics/Oceanography
Tetra Tech Marine Services

Sent from my Android phone


-----Original Message-----

**Comment by dgirardeau** [comment]
If it doesn't work with 2.10, then I'd be very interested to get a sample dataset to fix the bug ;)

**Comment by Dbhericks** [comment]
To test this should i have to select only the top level groups and apply?

Or do I have to select every object pointcloud,mesh,shp, that ONLY has global shift scale? I have viewports, saved labels etc too.

Ive tried both. Depending on what is selected in DB sometimes the edit global shift is not available.



David B Hericks, PMP
Principal Oceanographer/ Hydrographer
Hydrography/Geophysics/Oceanography
Tetra Tech Marine Services

Sent from my Android phone


-----Original Message-----

**Comment by dgirardeau** [comment]
The option is enabled as soon as you have either one cloud, one mesh or one polyline inside your selection.

I believe it may be possible to make CC crash if another type of entity is in the selection at the same time. Can you confirm this?

**Comment by dgirardeau** [comment]
Thanks for the feedback.

I already fixed the probably cause of this issue in the online 2.10.alpha version.
