### ISSUE TITLE
Not enough digits on global translate text entry

### ISSUE THREAD

**Issue by qume** [CloudCompare/CloudCompare#781]
## Current Behavior

You can enter apx 8 digits into the x/y/z global scene shift / local origin. When working in geographic projections, sometimes this means that there isn't room to have any precision after the decimal point.

## Expected Behavior

12 digits would work for most situations

## Your Environment
* CC Version: 
Latest
* OS & Version: 
Windows 10 x64

**Comment by dgirardeau** [comment]
Just for my understanding, what is the goal of setting a Global Shift with such a precision? Because the aim of the Global Shift is to avoid losing precision, but there's no need to go into so much details. Or do you want the high precision to translate a cloud from a local coordinate system to a global one? (calling the 'Edit > Edit Global Shift' option)

**Comment by qume** [comment]
Some times a pointcloud or mesh will be in a projection where it's a
long way from the origin, such as 12345678.123, and we work with it both
in local origin and in actual position depending on the part of the
process. Being able to specify the global shift to this precision would
be useful, and because of the precision we are working to, we need at
least two digits after the decimal, preferably three.
Hope this helps, and thanks again for the amazing work you do

--
  Luke Reid
  luke@reid.org.nz



On Tue, Sep 11, 2018, at 7:09 AM, Daniel Girardeau-Montaut wrote:
> Just for my understanding, what is the goal of setting a Global Shift
> with such a precision? Because the aim of the Global Shift is to avoid
> losing precision, but there's no need to go into so much details. Or
> do you want the high precision to translate a cloud from a local
> coordinate system to a global one? (calling the 'Edit > Edit Global
> Shift' option)> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].

Links:

  1. https://github.com/CloudCompare/CloudCompare/issues/781#issuecomment-420026254

**Comment by dgirardeau** [comment]
Well, if you input 12345678 as Global Shift (in your example), you already have a precision better than 1e-7 times the largest dimension of the bounding-box. And actually, because of the way floating point operations are done, going lower won't actually increase the precision... (the only way to optimize it a little bit further would be to use the center of the bounding-box instead of the first point of the cloud for instance - but in most cases we don't know the center of the bounding-box before actually loading the points).

**Comment by dgirardeau** [comment]
Okay, I've increased the number of digits when calling the 'Edit > Edit Global Shift & Scale' dialog. For now you'll have 6 digits instead of 2. Hope it will be sufficient (the filed is not that long).

I've updated the 2.10.alpha version online.
