### ISSUE TITLE
Statistical Outlier Removal (SOR) computation time varies significantly

### ISSUE THREAD

**Issue by SBCV** [CloudCompare/CloudCompare#816]
## Current Behavior
I have two (rather small) point clouds of similar size (w.r.t to number of points) obtained by stereo matching. For the first point cloud (5.800 points) SOR takes more than 4 minutes to finish - the second point cloud (8.300 points) is processed within 1 second.

I understand that the structure of the octree is different for both point clouds, but I am still surprised that the first point cloud takes 250 times longer than the second point cloud to be processed.  

While the first point cloud is being processed a popup window appears and shows the following: 
	Octree Level 13
	Cells 1398
	Average population 4.18 (+/- 4.48)
	Max population: 35

## Steps to Reproduce
Download both PLY files:
[https://www.dropbox.com/s/gpkvm47wrgeun0z/cloud_compare_SOR.zip](https://www.dropbox.com/s/gpkvm47wrgeun0z/cloud_compare_SOR.zip)
Open the files in CC and click on SOR
Take a cup of coffee and wait until the first computation finishes ;)

## Context/Comments
Does anybody have any experiences with the SOR implementation? Is that the expected behaviour?

## Your Environment
* CC Version: 
       I tested it with two different CC versions
             1.)  commit a9337c182e688d69be60b3664162a7b56e7353ac      (1.5.2018)
             2.)  commit f3edf8f947f197770c88c18e683d01e4daf1d660             (5.12.2018)
* OS & Version: Ubuntu 14.04
* Graphics card: GTX 1080 Ti

**Comment by dgirardeau** [comment]
Ah! Your slow cloud is quite peculiar ;) I believe it's the tails of very distant points that tricks the SOR algorithm.

This algorithm takes a given number of neighbors (k) around each point and filters the point out based on its relative distance / position to the neighbors.

Extracting the k nearest neighbors with such clouds is the tricky part here as the points are quite far from each other. If the algorithm decides to do it at a small octree level (this is how CC's octree is used) then it will be very fast on the dense parts of the cloud, and ultra slow on the very low density parts... You have the option of filtering out these points first by using another tool (such as the 'Label Connected Components' one). Or use the other version of the SOR algorithm (the 'Tools > Noise' filter) that can be used with a fixed neighborhood radius instead of a number of neighbors (so that the algorithm is much more stable).

**Comment by SBCV** [comment]
Hi, 
thank you for the quick reply. 

Although I understand your argument, I still find it a bit surprising that 51 remote points can hurt the computation of 5.846 points that much (i.e. a factor of 250). 

Thank you for pointing out those methods - I will play a bit with these! The "label connected components" worked quite well in that example :)

**Comment by dgirardeau** [comment]
To give you an idea, the level 13 of the octree has virtually 512 more cells than the level 10. Due to how we use the octree in CC, this has a huge impact on the computation time...
