### ISSUE TITLE
constexpr with floating operation, invalid with gcc and CGAL

### ISSUE THREAD

**Issue by bartoszek** [CloudCompare/CloudCompare#835]
There is a small problem with `constexpr` and CGAL. Code calling CGAL has to be devoided of a float operation in `constexpr` as there is a problem to kept FENV in GCC compiler.
_problem introduced in_ #832 
_CGAL rationale_ https://github.com/CGAL/cgal/issues/3180

**Comment by rjanvier** [comment]
cgal marked it as "won't fix", so I afraid as long as we link with cgal it will be a "won't fix" too i.e. no float in constexpr, at least for GCC. 
cc @asmaloney .

**Comment by asmaloney** [comment]
I'm not finding much of a rationale there.

Having this compiler flag propagate to all user code is problematic - you cannot use something as simple (and allowed by the standard) as `constexpr double foo = 1.0 / 42.0;` in your code anymore.

If we end up including other libraries that use constexpr as well, what do we do?

**Comment by rjanvier** [comment]
Wz can also replace cgal by the news QHULL revision that do constrained Delaunay triangulation. I don't know how it compare vs cgal in term of speed and robustness. The other by product could be in license compatibility. Part of cgal we use are GPL so it's viral...

**Comment by asmaloney** [comment]
This one? 

https://github.com/qhull/qhull

**Comment by rjanvier** [comment]
yes Qhull 2018.0.1, we already embed one version of qhull (for qhpr)

**Comment by bartoszek** [comment]
[`naive` patch for linux build.](https://aur.archlinux.org/cgit/aur.git/plain/constexpr.patch?h=cloudcompare-git)

**Comment by AlexandrParkhomenko** [comment]
oops, I try add this




gcc (GCC) 8.2.1 20181127 compilation error

**How to reproduce**
MAKE and out:
CloudCompare/libs/qCC_db/ccCameraSensor.cpp:56:54:
 error: ‘(5.4500000000000002e+0 * 1.0e-3)’ is not a constant expression
  constexpr float focal_mm  = static_cast<float>(5.45 * 1.0e-3); // focal length (real distance in meter)


**Expected behaviour**

using here "const" or dont using multiply "*"

**Additional context**


Please apply this patch:
https://aur.archlinux.org/cgit/aur.git/tree/constexpr.patch?h=cloudcompare-git


**Your environment**
 - CC Version (or git hash/tag): 2.10.2.r206.g7699efd9
 - OS & Version: https://aur.archlinux.org/packages/cloudcompare-git/
 - Graphics card:
 - Qt Version (if compiling): 5.12.2-1

**Comment by asmaloney** [comment]
@AlexandrParkhomenko This is a [CGAL issue](https://github.com/CGAL/cgal/issues/3180). They are using a compiler flag that propagates through user code and breaks simple things like `constexpr`.
