### ISSUE TITLE
Move CCLib to its own repo

### ISSUE THREAD

**Issue by asmaloney** [CloudCompare/CloudCompare#897]
**Describe the feature you would like**

Since CCLib can be built and used under LGPL outside of CC, we should separate it into its own repo and include it as a submodule.

This will make it easier for others to build and use. It will also provide better visibility for the library since it's hidden in CC right now!

**Additional context**

This came up in the discussion about PR #893.

**Comment by rjanvier** [comment]
I'm not sure to be 100% in favor of that change. The visibility argument is really good, but I think submodules are generally "no such a good idea" (TM) because the workflow could be quickly a pain. In another hand changes in CCLib are no so frequent so, in this specific case, it could be "smooth".
Regards,
Romain

**Comment by asmaloney** [comment]
> I think submodules are generally "no such a good idea" (TM)  because the workflow could be quickly a pain

Can you maybe elaborate on this? What part of the workflow?

**Comment by rjanvier** [comment]
I think there ate a bunch of examples over the web and I also think you are already aware of these. But here are two things that come to my mind
First it’s always inconvenient for newcomers because they won’t think to clone —recursive
Second a change commutes in CClib will require  a commit in CC repo. As I wrote since CClib is stable it shouldn’t be a big deal...

**Comment by asmaloney** [comment]
> I think there ate a bunch of examples over the web and I also think you are already aware of these.

I'm not - that's why I asked for clarification! Could you perhaps point me at (recent) examples where submodules are a major issue? Maybe there are use-cases I'm missing?

I'm using several repos with multiple submodules and I've found it really makes things easier overall.

> First it’s always inconvenient for newcomers because they won’t think to clone —recursive

I agree this used to be an issue a couple years ago when submodules were "new", but it can now be handled directly in cmake (by using a cmake git module). There is a way to automatically pull submodules and keep them up-to-date (I'm using it in another project).

> Second a change commutes in CClib will require a commit in CC repo.

But we want this, don't we? If CCLib is used as a separate library, then having it in its own repo helps keep it working in the non-CC use case (see #893). It forces the separation and also makes any changes demonstrate intent. It would get treated like any other 3rd party repo.

**Comment by asmaloney** [comment]
Here's the cmake git submodule handling that I mentioned earlier:

https://cliutils.gitlab.io/modern-cmake/chapters/projects/submodule.html

I'm sure there are other ways as well, but this one is working well for me.

**Comment by rjanvier** [comment]
Ok that looks simple enough.

**Comment by asmaloney** [comment]
BTW - that [Modern CMake](https://cliutils.gitlab.io/modern-cmake) site is great!

I started a new project from scratch using their recommendations and I even hate cmake _a little bit_ less now. 😜

**Comment by dgirardeau** [comment]
I am ok to move CC_CORE_LIB to a submodule.

**Comment by asmaloney** [comment]
Completed in 72f5c682a5bd1203d55984344bffbcf1894c7a3a
