### ISSUE TITLE
Sphere Fitting Sample Count

### ISSUE THREAD

**Issue by WargodHernandez** [CloudCompare/CloudCompare#912]
**Describe the bug**
GeometricalAnalysisTools::detectSphereRobust
Does not include point count evaluation when determining the number of samples to perform
a cloud with > 4 points will always be 71 samples with 0.99 Confidence and 0.5 outlier ratio.
a cloud with 5 points or 15 million points will use 71 samples 

I've included the relevant lines of code from GeometricalAnalysisTools.cpp

const` unsigned p = 4;
unsigned n = cloud->size();
unsigned m = 1;
	if (n > p)
	{
		m = static_cast<unsigned>(log(1.0 - confidence) / log(1.0 - pow(1.0 - outliersRatio, static_cast<double>(p))));
	}

**Comment by dgirardeau** [comment]
I know that it's disturbing, but if you refer to the article (https://members.loria.fr/moberger/Enseignement/Master2/Documents/ZhangIVC-97-01.pdf) you'll see that the number of samples 'm' doesn't depend on the number of points in the cloud (below equation (29) on page 28). This is because it is assumed that a portion of these points are part of the detected shape (1-epsilon). So you only want to make enough draws to find a set of p (=4 or 5) points that doesn't have any outlier. Therefore the number of draws only depend on 'p' and 'epsilon'.
