### ISSUE TITLE
install on windows 10 by installer, can NOT start

### ISSUE THREAD

**Issue by Harold2017** [CloudCompare/CloudCompare#969]
**Describe the bug**
As the event log shows:

![error](https://user-images.githubusercontent.com/29817247/66544997-4352b580-eb6c-11e9-9576-532e07bad188.png)

**Your environment**
 - CC Version (or git hash/tag):CloudCompare 2.10.2 installer version
 - OS & Version:Windows 10 Home 64bit
 - Graphics card:Intel® Iris® Plus Graphics 655 (i5-8259U)
 - Qt Version (if compiling): NA

**Comment by dgirardeau** [comment]
There's indeed a known incompatibility with Qt 5 (the framework on which CloudCmpare is based) and a lot of old Intel chipsets.

If you have a dual graphic card, you should force the real GPU to be used when launching CloudCompare.

Otherwise... maybe try to update the driver? (just in case, sadly it rarely solves this issue).
