### ISSUE TITLE
Entry point not found when program start.

### ISSUE THREAD

**Issue by nirenyang** [CloudCompare/CloudCompare#989]
Entry point not found when program start.

![Snap1](https://user-images.githubusercontent.com/1759638/68311455-890f8900-00ec-11ea-9bcb-495f3e0fbc4d.png)

**Comment by dgirardeau** [comment]
See https://github.com/CloudCompare/CloudCompare/issues/966

**Comment by LFE-bourne** [comment]
Had this same error today, specifically the gdal202.dll.

CloudCompare was working in its usual flawless manner, closed it down and upon attempted restart, it failed. Have tried reboot/re-install, disk check and scannow. Any ideas why this happened all of the sudden?

**Comment by LFE-bourne** [comment]
Had this same error today, specifically the gdal202.dll.

CloudCompare was working in its usual flawless manner, closed it down and upon attempted restart, it failed. Have tried reboot/re-install, disk check and scannow. Any ideas why this happened all of the sudden @dgirardeau ? #989 
Duplicate of #989

**Comment by dgirardeau** [comment]
Have you installed the Faro plugin / LS SDK? Or have you updated any Faro software maybe?

**Comment by LFE-bourne** [comment]
Yes I selected the checkbox for the plugin.
Ahh yes, updated FARO Scene

**Comment by dgirardeau** [comment]
Well, sadly you encounter the same issue as many others, due to a conflict between two DLLs of the same library but of different versions (one is used by CC, and the other is used by the FARO LS SDK). Not everyone has the issue and sadly we haven't found the solution yet... (apart from rolling back to a previous version for one of the software at stake).
